[pytest]
markers =
    UI: marks tests as UI tests (deselect with '-m "not UI"')
    UI_testbed: marks tests as UI testbed tests

testpaths = completed

python_files = test_*.py
python_classes = Test*
python_functions = test_*