name: Enforce Promotion Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  check-promotion:
    runs-on: ubuntu-latest

    steps:
      - name: Verify branch promotion
        run: |
          echo "Source Branch: ${{github.head_ref}}"
          echo "Target Branch: ${{github.base_ref}}"
          
          # Main will only accept PRs from UAT
          if [["${{github.base_ref}}" == "main" && "${{github.head_ref}}" != "trailblazers-uat"]]; then
            echo "Failed: Main will only accept PRs from UAT"
            exit 1
          fi
          
          # Main will only accept PRs from UAT
          if [["${{github.base_ref}}" == "trailblazers-uat" && "${{github.head_ref}}" != "trailblazers-tst"]]; then
            echo "Failed: UAT will only accept PRs from TST"
            exit 1
          fi
          
          # Main will only accept PRs from UAT
          if [["${{github.base_ref}}" == "trailblazers-tst" && "${{github.head_ref}}" != "trailblazers-*"]]; then
            echo "Failed: TST will only accept PRs from a branch prefixed with trailblazers-"
            exit 1
          fi
          
          echo "Promotion valid."