name: "Integration Testing"

on:
  pull_request:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "Trailblazers"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "test-workplace"
  TF_WORKSPACE_ID: "ws-LG99RLWhhrv1UV1y"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  TF_VAR_deploy_env: '"test"'
  CONFIG_DIRECTORY: "./terraform"
  TF_VAR_ses_identity_arn: '"${{vars.SES_IDENTITY_ARN}}"'
  TF_VAR_step_ca_version: '"${{ vars.STEP_CA_VERSION }}"'

jobs:
  terraform:
    name: "Integration Testing"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.0
        id: destroy-run-a
        with:
          workspace: test0-workspace
          is_destroy: true
        if: ${{ always() }}

      - name: Destroy
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.0
        with:
          run: ${{ steps.destroy-run-a.outputs.run_id }}
        if: ${{ always() && fromJSON(steps.destroy-run-a.outputs.payload).data.attributes.actions.IsConfirmable }}

      - name: Create Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.0
        id: destroy-run-b
        with:
          workspace: test1-workspace
          is_destroy: true
        if: ${{ always() }}

      - name: Destroy
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.0
        with:
          run: ${{ steps.destroy-run-b.outputs.run_id }}
        if: ${{ always() && fromJSON(steps.destroy-run-b.outputs.payload).data.attributes.actions.IsConfirmable }}

      - name: Create Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.0
        id: destroy-run-c
        with:
          workspace: test2-workspace
          is_destroy: true
        if: ${{ always() }}

      - name: Destroy
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.0
        with:
          run: ${{ steps.destroy-run-c.outputs.run_id }}
        if: ${{ always() && fromJSON(steps.destroy-run-c.outputs.payload).data.attributes.actions.IsConfirmable }}